# Generated by Django 6.0.2 on 2026-02-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedingtime',
            old_name='time',
            new_name='datetime',
        ),
    ]
